// <auto-generated />
using System;
using Api_RenoExpress.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api_RenoExpress.Migrations
{
    [DbContext(typeof(InventarioDBContext))]
    partial class InventarioDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Api_RenoExpress.Entities.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FechaCompra");

                    b.Property<int>("IdProveedor");

                    b.Property<string>("NoDocumento");

                    b.HasKey("IdCompra");

                    b.ToTable("Compra");
                });

            modelBuilder.Entity("Api_RenoExpress.Entities.DetalleCompra", b =>
                {
                    b.Property<int>("IdDetalleCompra")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad");

                    b.Property<int>("IdCompra");

                    b.Property<int>("IdProducto");

                    b.Property<decimal>("PrecioTotal");

                    b.HasKey("IdDetalleCompra");

                    b.ToTable("DetalleCompra");
                });

            modelBuilder.Entity("Api_RenoExpress.Entities.DetalleVenta", b =>
                {
                    b.Property<int>("IdDetalleVenta")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cantidad");

                    b.Property<int>("IdProducto");

                    b.Property<int>("IdVenta");

                    b.Property<decimal>("SubTotal");

                    b.HasKey("IdDetalleVenta");

                    b.ToTable("DetalleVenta");
                });

            modelBuilder.Entity("Api_RenoExpress.Entities.Inventario", b =>
                {
                    b.Property<int>("IdInventario")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CantidadExistencia");

                    b.Property<int>("IdProducto");

                    b.HasKey("IdInventario");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("Api_RenoExpress.Entities.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreProducto");

                    b.Property<int>("PrecioUnitario");

                    b.Property<int>("TipoProducto");

                    b.HasKey("IdProducto");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Api_RenoExpress.Entities.Sucursal", b =>
                {
                    b.Property<int>("IdSucursal")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Correo");

                    b.Property<string>("Direccion");

                    b.Property<string>("Telefono");

                    b.HasKey("IdSucursal");

                    b.ToTable("Sucursal");
                });

            modelBuilder.Entity("Api_RenoExpress.Entities.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Factura");

                    b.Property<DateTime>("FechaVenta");

                    b.Property<int>("IdCliente");

                    b.Property<int>("IdSucursal");

                    b.HasKey("IdVenta");

                    b.ToTable("Venta");
                });
#pragma warning restore 612, 618
        }
    }
}
